---

-  hosts: all
   become: true
   pre_tasks:

   -  name: Install Updates (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

-  hosts: ubuntu
   become: true
   roles:
     -  Ubuntu
